/* MedTodo for Obsidian -- generated by tools/build-plugin.js. Do not edit.
   Edit the shared sources in the repository root and rebuild. */

// ===== ui.js =======================================================
(function (module, exports) {
// The app's markup, in one place so the web page and the Obsidian plugin mount
// exactly the same DOM. Static and trusted -- no task data is interpolated here;
// everything user-supplied is set with textContent at render time.
(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = api;
  }
  if (root) {
    root.MedTodoUI = api;
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const APP_MARKUP = `
    <div class="app">
      <header class="app__header">
        <div>
          <h1>Todo List</h1>
          <p>Clinical, academic, and home tasks in one place.</p>
        </div>
        <div class="app__meta">
          <button id="season-chip" class="season-chip" type="button"></button>
          <span id="sync-status" class="sync-status"></span>
          <button id="clear-completed" class="secondary">Clear completed</button>
        </div>
      </header>

      <div class="layout">
        <main class="main">
          <section class="card card--capture">
            <div class="quick-capture">
              <input id="quick-capture-input" type="text"
                     placeholder="Add a task&hellip; e.g. Call Dr. Smith next friday 2pm #urgent !high clinical" />
              <button id="quick-capture-btn" class="primary">Add</button>
            </div>
            <p class="muted capture-hint" id="capture-hint">
              Type naturally: a date (<em>tomorrow</em>, <em>next monday</em>, <em>in 3 days</em>),
              a time (<em>2pm</em>), <em>#tag</em>, <em>!high</em>, and a category.
            </p>
          </section>

          <section class="card">
            <div class="card__header">
              <h2>Schedule</h2>
              <span id="task-count" class="muted">0 tasks</span>
            </div>

            <div class="tabs" role="tablist" aria-label="Task views">
              <button class="tab active" type="button" role="tab" aria-selected="true" data-view="today">
                Today <span id="today-count" class="tab__count"></span>
              </button>
              <button class="tab" type="button" role="tab" aria-selected="false" data-view="week">
                Week <span id="week-count" class="tab__count"></span>
              </button>
              <button class="tab" type="button" role="tab" aria-selected="false" data-view="all">
                All
              </button>
            </div>

            <div class="view" data-panel="today">
              <div id="today-schedule" class="today-schedule">
                <p class="muted">No tasks scheduled for today.</p>
              </div>
            </div>

            <div class="view" data-panel="week" hidden>
              <div id="week-view" class="week-view">
                <p class="muted">No tasks scheduled this week.</p>
              </div>
            </div>

            <div class="view" data-panel="all" hidden>
              <div class="filter-row">
                <div class="filters" role="group" aria-label="Filter tasks">
                  <button class="filter active" type="button" data-filter="all">All</button>
                  <button class="filter" type="button" data-filter="active">Active</button>
                  <button class="filter" type="button" data-filter="completed">Completed</button>
                </div>
                <input id="search-input" type="search" placeholder="Search tasks" />
              </div>
              <div class="filter-row">
                <div class="category-filters" role="group" aria-label="Filter by category">
                  <button class="category-filter active" type="button" data-category="">All</button>
                  <button class="category-filter" type="button" data-category="work">Work</button>
                  <button class="category-filter" type="button" data-category="home">Home</button>
                  <button class="category-filter" type="button" data-category="research">Research</button>
                  <button class="category-filter" type="button" data-category="clinical">Clinical</button>
                  <button class="category-filter" type="button" data-category="teaching">Teaching</button>
                </div>
              </div>
              <div class="filter-row filter-row--date">
                <label class="field field--inline">
                  <span>Jump to date</span>
                  <input id="calendar-date" type="date" />
                </label>
                <button id="clear-date-filter" class="secondary" type="button">Clear date</button>
              </div>
              <ul id="task-list" class="task-list"></ul>
            </div>
          </section>

          <details class="card card--tool">
            <summary class="tool__summary">Add with all fields</summary>
            <p class="muted">Start from a template, or fill in everything by hand.</p>
            <div class="template-buttons">
              <button class="template-btn secondary" type="button" data-template="patient-referral">New Patient Referral</button>
              <button class="template-btn secondary" type="button" data-template="research-review">Research Paper Review</button>
              <button class="template-btn secondary" type="button" data-template="conference-prep">Conference Prep</button>
              <button class="template-btn secondary" type="button" data-template="family-event">Family Event</button>
            </div>
            <form id="task-form" autocomplete="off">
              <label class="field">
                <span>New task</span>
                <input id="task-input" type="text" placeholder="Add a task" required />
              </label>
              <label class="field">
                <span>Notes</span>
                <input id="task-notes" type="text" placeholder="Optional details" />
              </label>
              <div class="form-row">
                <label class="field">
                  <span>Priority</span>
                  <select id="task-priority">
                    <option value="low">Low</option>
                    <option value="medium" selected>Medium</option>
                    <option value="high">High</option>
                  </select>
                </label>
                <label class="field">
                  <span>Category</span>
                  <select id="task-category">
                    <option value="work">Work</option>
                    <option value="home">Home</option>
                    <option value="research">Research</option>
                    <option value="clinical">Clinical</option>
                    <option value="teaching">Teaching</option>
                  </select>
                </label>
                <label class="field">
                  <span>Tag</span>
                  <input id="task-tag" type="text" placeholder="e.g. #urgent" />
                </label>
              </div>
              <div class="form-row">
                <label class="field">
                  <span>Due date</span>
                  <input id="task-due-date" type="date" />
                </label>
                <label class="field">
                  <span>Due time</span>
                  <input id="task-due-time" type="time" />
                </label>
                <label class="field">
                  <span>Recurrence</span>
                  <select id="task-recurrence">
                    <option value="">None</option>
                    <option value="daily">Daily</option>
                    <option value="weekly">Weekly</option>
                    <option value="monthly">Monthly</option>
                  </select>
                </label>
                <button type="submit" class="primary">Add task</button>
              </div>
            </form>
          </details>

          <section class="card" id="sync-card">
            <div class="card__header">
              <h2>Device Sync</h2>
            </div>
            <p class="muted">
              Tasks are encrypted on this device before anything is uploaded, so the
              server only ever holds ciphertext it cannot read.
              <strong>Clinical tasks are never uploaded</strong> &mdash; they stay only on
              the device that created them.
            </p>

            <div id="sync-setup">
              <div class="form-row">
                <label class="field">GitHub username
                  <input id="sync-owner" type="text" autocomplete="off" placeholder="e.g. adamskate123" />
                </label>
                <label class="field">Private repo name
                  <input id="sync-repo" type="text" autocomplete="off" placeholder="e.g. medtodo-sync" />
                </label>
              </div>
              <div class="form-row">
                <label class="field">Access token
                  <input id="sync-token" type="password" autocomplete="off" placeholder="github_pat_&hellip;" />
                </label>
                <label class="field">Passphrase
                  <input id="sync-passphrase" type="password" autocomplete="off" placeholder="Same on every device" />
                </label>
              </div>
              <p class="muted" style="font-size: 0.85rem;">
                The passphrase never leaves this device and cannot be reset. If you lose
                it, the synced data cannot be recovered.
                <a href="SYNC_SETUP.md">Setup instructions</a>
              </p>
              <div class="card__actions">
                <button id="sync-connect" class="primary" type="button">Connect this device</button>
              </div>
            </div>

            <div id="sync-connected" hidden>
              <p class="muted" id="sync-target"></p>
              <div class="card__actions">
                <button id="sync-now" class="primary" type="button">Sync now</button>
                <button id="sync-disconnect" class="danger" type="button">Disconnect this device</button>
              </div>
            </div>
          </section>

          <details class="card card--tool">
            <summary class="tool__summary">Calendar export</summary>
            <p class="muted">
              Export tasks with due dates to Google Calendar, Outlook, or Apple Calendar.
              High-priority tasks include a 15-minute reminder.
            </p>
            <div class="card__actions">
              <button id="export-calendar" class="primary" type="button">Export to Calendar (.ics)</button>
            </div>
          </details>

          <details class="card card--tool">
            <summary class="tool__summary">Obsidian (Markdown)</summary>
            <p class="muted">
              Export a Markdown checklist for an Obsidian note, or paste one in to import.
            </p>
            <div class="card__actions">
              <button id="export-markdown" class="secondary" type="button">Export to Markdown</button>
            </div>
            <textarea id="markdown-area" rows="8" placeholder="- [ ] Example task"></textarea>
            <div class="card__actions">
              <button id="import-markdown" class="primary" type="button">Import from Markdown</button>
              <button id="copy-markdown" class="secondary" type="button">Copy to clipboard</button>
            </div>
          </details>

          <details class="card card--tool">
            <summary class="tool__summary">Manual backup</summary>
            <p class="muted">
              A plain, <strong>unencrypted</strong> copy of every task, clinical ones
              included. Keep it somewhere you would be comfortable storing patient
              information.
            </p>
            <div class="card__actions">
              <button id="export-json" class="primary" type="button">Download Backup</button>
              <button id="import-json-btn" class="secondary" type="button">Restore from Backup</button>
              <input type="file" id="import-json-file" accept=".json" style="display: none;" />
            </div>
          </details>
        </main>
      </div>
    </div>

    <!-- Undo toast -->
    <div id="toast" class="toast" role="status" aria-live="polite" hidden>
      <span id="toast-message"></span>
      <button id="toast-action" class="toast__action" type="button">Undo</button>
    </div>

    <!-- Floating Quick Add Button -->
    <button id="floating-quick-add" class="floating-btn" title="Quick Add Task">+</button>

    <!-- Edit Task Modal -->
    <div id="edit-modal" class="modal" style="display: none;">
      <div class="modal-content">
        <div class="modal-header">
          <h2>Edit Task</h2>
          <button id="close-modal" class="close-btn">&times;</button>
        </div>
        <form id="edit-form">
          <label class="field">
            <span>Task title</span>
            <input id="edit-title" type="text" required />
          </label>
          <label class="field">
            <span>Notes</span>
            <input id="edit-notes" type="text" />
          </label>
          <div class="form-row">
            <label class="field">
              <span>Priority</span>
              <select id="edit-priority">
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
              </select>
            </label>
            <label class="field">
              <span>Category</span>
              <select id="edit-category">
                <option value="work">Work</option>
                <option value="home">Home</option>
                <option value="research">Research</option>
                <option value="clinical">Clinical</option>
                <option value="teaching">Teaching</option>
              </select>
            </label>
            <label class="field">
              <span>Tag</span>
              <input id="edit-tag" type="text" placeholder="e.g. #urgent" />
            </label>
          </div>
          <div class="form-row">
            <label class="field">
              <span>Due date</span>
              <input id="edit-due-date" type="date" />
            </label>
            <label class="field">
              <span>Due time</span>
              <input id="edit-due-time" type="time" />
            </label>
            <label class="field">
              <span>Recurrence</span>
              <select id="edit-recurrence">
                <option value="">None</option>
                <option value="daily">Daily</option>
                <option value="weekly">Weekly</option>
                <option value="monthly">Monthly</option>
              </select>
            </label>
          </div>
          <div class="modal-actions">
            <button type="button" id="cancel-edit" class="secondary">Cancel</button>
            <button type="submit" class="primary">Save Changes</button>
          </div>
        </form>
      </div>
    </div>
`;

  // Mount the markup into a container and hand back the container.
  function mount(root) {
    root.innerHTML = APP_MARKUP;
    return root;
  }

  return { APP_MARKUP, mount };
});

})(undefined, undefined);

// ===== todo-markdown.js ============================================
(function (module, exports) {
// The vault format: an ordinary Obsidian checklist that also round-trips the
// fields the app needs.
//
//   - [ ] Draft R01 aims #grant (due: 2026-09-11 09:00, priority: high, category: research) <!--medtodo {"id":"..."}-->
//
// Everything before the parenthesis is what a human reads and may edit by hand;
// edits to the title, tag, checkbox and metadata are all picked back up. The
// trailing HTML comment carries only what a person would not want to maintain
// (id and timestamps) and does not render in Obsidian.
(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = api;
  }
  if (root) {
    root.MedTodoMarkdown = api;
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const META_KEYS = ["due", "priority", "category", "every", "recurrence"];

  // Anchored at end of line so a title may contain anything, including
  // parentheses, "#", or an em dash -- the old splitter broke on those.
  const COMMENT_RE = /\s*<!--\s*medtodo\s*(\{.*\})\s*-->\s*$/;
  const META_RE = /\s*\(([^()]*)\)\s*$/;
  const TAG_RE = /\s(#[\w-]+)\s*$/;
  const CHECKBOX_RE = /^\s*[-*]\s*\[([ xX])\]\s?/;

  // JSON lives inside an HTML comment, so it must never contain "-->".
  // Escaping every ">" makes that impossible and stays valid JSON.
  function encodeJson(value) {
    return JSON.stringify(value).replace(/>/g, "\\u003e");
  }

  function looksLikeMetadata(text) {
    const parts = text.split(",").map((part) => part.trim()).filter(Boolean);
    if (!parts.length) return false;
    // Only treat a trailing parenthesis as metadata when every part is a known
    // key, so a title like "Review protocol (draft)" survives intact.
    return parts.every((part) => {
      const key = part.split(":")[0].trim().toLowerCase();
      return META_KEYS.includes(key) && part.includes(":");
    });
  }

  function parseMetadata(text) {
    const out = {};
    text.split(",").forEach((part) => {
      const index = part.indexOf(":");
      if (index === -1) return;
      const key = part.slice(0, index).trim().toLowerCase();
      out[key] = part.slice(index + 1).trim();
    });
    return out;
  }

  function serializeTask(task) {
    const checkbox = task.completed ? "- [x]" : "- [ ]";
    const meta = [];
    if (task.dueDate) {
      meta.push(`due: ${task.dueDate}${task.dueTime ? " " + task.dueTime : ""}`);
    }
    if (task.priority && task.priority !== "medium") {
      meta.push(`priority: ${task.priority}`);
    }
    if (task.category) meta.push(`category: ${task.category}`);
    if (task.recurrence) meta.push(`every: ${task.recurrence}`);

    const hidden = {
      id: task.id,
      createdAt: task.createdAt,
      updatedAt: task.updatedAt,
    };
    // Notes ride in the comment so they cannot collide with the metadata
    // parenthesis or the tag.
    if (task.notes) hidden.notes = task.notes;

    return [
      checkbox,
      " ",
      task.title,
      task.tag ? " " + task.tag : "",
      meta.length ? ` (${meta.join(", ")})` : "",
      ` <!--medtodo ${encodeJson(hidden)}-->`,
    ].join("");
  }

  function serializeTasks(tasks) {
    return tasks.map(serializeTask).join("\n");
  }

  function parseTaskLine(line) {
    const checkbox = CHECKBOX_RE.exec(line);
    if (!checkbox) return null;

    const completed = checkbox[1].toLowerCase() === "x";
    let rest = line.slice(checkbox[0].length);

    let hidden = {};
    const comment = COMMENT_RE.exec(rest);
    if (comment) {
      try {
        hidden = JSON.parse(comment[1]) || {};
      } catch (error) {
        hidden = {};
      }
      rest = rest.slice(0, comment.index);
    }

    let meta = {};
    const metaMatch = META_RE.exec(rest);
    if (metaMatch && looksLikeMetadata(metaMatch[1])) {
      meta = parseMetadata(metaMatch[1]);
      rest = rest.slice(0, metaMatch.index);
    }

    let tag = "";
    const tagMatch = TAG_RE.exec(rest);
    if (tagMatch) {
      tag = tagMatch[1];
      rest = rest.slice(0, tagMatch.index);
    }

    let title = rest.trim();
    let legacyNotes = "";
    // The pre-v2 format wrote "Title — notes" with no trailing comment. Only
    // apply that split when there is no comment, so a title containing an em
    // dash is left alone in the current format.
    if (!comment && title.includes(" \u2014 ")) {
      const parts = title.split(" \u2014 ");
      title = parts[0].trim();
      legacyNotes = parts.slice(1).join(" \u2014 ").trim();
    }
    if (!title) return null;

    let dueDate = "";
    let dueTime = "";
    if (meta.due) {
      const [datePart, timePart] = meta.due.split(/\s+/);
      dueDate = datePart || "";
      dueTime = timePart || "";
    }

    return {
      id: hidden.id || "",
      title,
      notes: hidden.notes || legacyNotes,
      priority: meta.priority || "medium",
      category: meta.category || "work",
      tag,
      dueDate,
      dueTime,
      recurrence: meta.every || meta.recurrence || "",
      completed,
      createdAt: hidden.createdAt || "",
      updatedAt: hidden.updatedAt || "",
      deleted: false,
    };
  }

  function parseTasks(markdown) {
    if (!markdown) return [];
    return markdown
      .split(/\r?\n/)
      .map(parseTaskLine)
      .filter(Boolean);
  }

  return { serializeTask, serializeTasks, parseTaskLine, parseTasks };
});

})(undefined, undefined);

// ===== app.js ======================================================
(function (module, exports) {
// The app, as a factory so it can be created against any container and any
// storage backend. The web page passes #app-root and localStorage; the Obsidian
// plugin passes its view container and a vault-backed adapter.
//
// `storage` only needs getItem(key) and setItem(key, value). It is synchronous
// by design -- the Obsidian adapter serves reads from an in-memory cache that is
// primed before the app is created, and flushes writes to the vault in the
// background, which keeps every call site here simple.
function createMedTodoApp(options) {
  const root = options.root;
  const storage = options.storage;

  const STORAGE_KEY = "todo.tasks";

  // --- Storage schema --------------------------------------------------------
  // v1 stored a bare array of tasks. v2 stores { version, tasks } and gives every
  // task an updatedAt plus a soft-delete flag, which is what makes cross-device
  // merging possible at all.
  // These must stay above the `let tasks = loadTasks()` call below: loadTasks()
  // reads them, and a `const` referenced before its initializer throws.
  const SCHEMA_VERSION = 2;
  const TOMBSTONE_RETENTION_DAYS = 90;

  // Form elements
  const taskForm = root.querySelector("#task-form");
  const taskInput = root.querySelector("#task-input");
  const taskNotes = root.querySelector("#task-notes");
  const taskPriority = root.querySelector("#task-priority");
  const taskCategory = root.querySelector("#task-category");
  const taskTag = root.querySelector("#task-tag");
  const taskDueDate = root.querySelector("#task-due-date");
  const taskDueTime = root.querySelector("#task-due-time");
  const taskRecurrence = root.querySelector("#task-recurrence");

  // Display elements
  const taskList = root.querySelector("#task-list");
  const taskCount = root.querySelector("#task-count");
  const searchInput = root.querySelector("#search-input");
  const filterButtons = root.querySelectorAll(".filter");
  const categoryFilterButtons = root.querySelectorAll(".category-filter");
  const clearCompletedButton = root.querySelector("#clear-completed");

  // Quick capture
  const quickCaptureInput = root.querySelector("#quick-capture-input");
  const quickCaptureBtn = root.querySelector("#quick-capture-btn");
  const floatingQuickAddBtn = root.querySelector("#floating-quick-add");

  // Templates
  const templateButtons = root.querySelectorAll(".template-btn");

  // Markdown
  const markdownArea = root.querySelector("#markdown-area");
  const exportMarkdownButton = root.querySelector("#export-markdown");
  const importMarkdownButton = root.querySelector("#import-markdown");
  const copyMarkdownButton = root.querySelector("#copy-markdown");

  // JSON Export/Import
  const exportJsonButton = root.querySelector("#export-json");
  const importJsonButton = root.querySelector("#import-json-btn");
  const importJsonFile = root.querySelector("#import-json-file");

  // Calendar Integration
  const exportCalendarButton = root.querySelector("#export-calendar");
  const todaySchedule = root.querySelector("#today-schedule");
  const todayCount = root.querySelector("#today-count");
  const weekView = root.querySelector("#week-view");

  // Date filter
  const calendarDate = root.querySelector("#calendar-date");
  const clearDateFilterButton = root.querySelector("#clear-date-filter");

  // View tabs
  const tabButtons = root.querySelectorAll(".tab");
  const viewPanels = root.querySelectorAll(".view");
  const weekCount = root.querySelector("#week-count");

  // Season
  const seasonChip = root.querySelector("#season-chip");

  // Undo toast
  const toast = root.querySelector("#toast");
  const toastMessage = root.querySelector("#toast-message");
  const toastAction = root.querySelector("#toast-action");

  // Edit modal
  const editModal = root.querySelector("#edit-modal");
  const editForm = root.querySelector("#edit-form");
  const closeModalBtn = root.querySelector("#close-modal");
  const cancelEditBtn = root.querySelector("#cancel-edit");
  const editTitle = root.querySelector("#edit-title");
  const editNotes = root.querySelector("#edit-notes");
  const editPriority = root.querySelector("#edit-priority");
  const editCategory = root.querySelector("#edit-category");
  const editTag = root.querySelector("#edit-tag");
  const editDueDate = root.querySelector("#edit-due-date");
  const editDueTime = root.querySelector("#edit-due-time");
  const editRecurrence = root.querySelector("#edit-recurrence");

  // State
  let tasks = loadTasks();
  let activeFilter = "all";
  let activeView = "today";
  let activeCategory = "";
  let activeDate = "";
  let currentEditingTaskId = null;

  // Task templates
  const TEMPLATES = {
    "patient-referral": {
      title: "New Patient Referral",
      notes: "Review referral, Schedule initial consultation, Prepare case history",
      priority: "high",
      category: "clinical",
      tag: "#patient",
    },
    "research-review": {
      title: "Research Paper Review",
      notes: "Read abstract, Review methodology, Analyze results, Write summary",
      priority: "medium",
      category: "research",
      tag: "#paper",
    },
    "conference-prep": {
      title: "Conference Preparation",
      notes: "Prepare abstract, Create presentation slides, Rehearse talk, Book travel",
      priority: "medium",
      category: "research",
      tag: "#conference",
    },
    "family-event": {
      title: "Family Event",
      notes: "Plan activity, Confirm schedules, Make arrangements",
      priority: "low",
      category: "home",
      tag: "#family",
    },
  };

  function generateId() {
    if (crypto.randomUUID) {
      return crypto.randomUUID();
    }
    return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
  }

  // --- Local calendar dates --------------------------------------------------
  // toISOString() returns a UTC date. Using it to answer "what day is it" shifts
  // the calendar day for anyone not on UTC -- e.g. after ~8pm US Eastern it
  // reports tomorrow, so "Today's Schedule" silently showed the wrong day every
  // evening. Every *calendar date* (dueDate, today, the week grid) goes through
  // these helpers. Point-in-time stamps (createdAt/updatedAt) stay ISO/UTC.
  function toLocalDateString(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  }

  function parseLocalDate(dateString) {
    const [year, month, day] = dateString.split("-").map(Number);
    return new Date(year, month - 1, day);
  }

  function todayString() {
    return toLocalDateString(new Date());
  }

  // Build an element without going through innerHTML, so task titles can never
  // be parsed as markup.
  function el(tag, className, text) {
    const node = document.createElement(tag);
    if (className) node.className = className;
    if (text != null) node.textContent = text;
    return node;
  }

  function normalizeTask(task) {
    const createdAt = task.createdAt || new Date().toISOString();
    return {
      notes: "",
      tag: "",
      dueDate: "",
      dueTime: "",
      recurrence: "",
      priority: "medium",
      category: "work",
      completed: false,
      ...task,
      createdAt,
      // Pre-v2 tasks have no updatedAt. Seeding it from createdAt keeps them from
      // looking newer than they are during a merge.
      updatedAt: task.updatedAt || createdAt,
      deleted: task.deleted === true,
    };
  }

  // Deleted tasks are kept as tombstones so a delete on one device wins over a
  // stale copy on another instead of the task reappearing. They are dropped once
  // every device has certainly seen the deletion.
  function purgeOldTombstones(list) {
    const cutoff = Date.now() - TOMBSTONE_RETENTION_DAYS * 24 * 60 * 60 * 1000;
    return list.filter((task) => {
      if (!task.deleted) return true;
      const at = Date.parse(task.deletedAt || task.updatedAt || "");
      return Number.isNaN(at) || at > cutoff;
    });
  }

  function loadTasks() {
    const raw = storage.getItem(STORAGE_KEY);
    if (!raw) {
      return [];
    }
    try {
      const parsed = JSON.parse(raw);
      const list = Array.isArray(parsed)
        ? parsed
        : parsed && Array.isArray(parsed.tasks)
        ? parsed.tasks
        : [];
      return purgeOldTombstones(list.map(normalizeTask));
    } catch (error) {
      // Returning [] here means the next saveTasks() would overwrite whatever is
      // in storage, so keep a copy of the unreadable value first.
      console.error("Unable to read saved tasks; preserving a copy", error);
      try {
        storage.setItem(`${STORAGE_KEY}.corrupt.${Date.now()}`, raw);
      } catch (nested) {
        console.error("Could not preserve unreadable tasks", nested);
      }
      return [];
    }
  }

  function saveTasks() {
    storage.setItem(
      STORAGE_KEY,
      JSON.stringify({ version: SCHEMA_VERSION, tasks })
    );
    // Debounced; a no-op until sync is configured.
    if (window.MedTodoSync) {
      window.MedTodoSync.scheduleAutosync();
    }
  }

  // Everything the user should actually see. Tombstones stay in `tasks` for sync
  // but must never reach the UI.
  function liveTasks() {
    return tasks.filter((task) => !task.deleted);
  }

  // Merge two task lists by id: newest updatedAt wins. A deletion is just a
  // tombstone with a timestamp, so it competes on the same footing as an edit.
  function mergeTaskLists(mine, theirs) {
    const byId = new Map();
    mine.map(normalizeTask).forEach((task) => byId.set(task.id, task));
    theirs.map(normalizeTask).forEach((incoming) => {
      const existing = byId.get(incoming.id);
      if (!existing) {
        byId.set(incoming.id, incoming);
        return;
      }
      const mineAt = Date.parse(existing.updatedAt) || 0;
      const theirsAt = Date.parse(incoming.updatedAt) || 0;
      byId.set(incoming.id, theirsAt > mineAt ? incoming : existing);
    });
    return Array.from(byId.values());
  }

  function addTask({ title, notes, priority, category, tag, dueDate, dueTime, recurrence }) {
    if (!title.trim()) {
      return;
    }

    const now = new Date().toISOString();
    const task = {
      id: generateId(),
      title: title.trim(),
      notes: notes.trim(),
      priority,
      category,
      tag: tag.trim(),
      dueDate,
      dueTime: dueTime || "",
      recurrence: recurrence || "",
      completed: false,
      createdAt: now,
      updatedAt: now,
      deleted: false,
    };

    tasks.unshift(task);
    saveTasks();
    render();

    return task;
  }

  function updateTask(id, updates) {
    const now = new Date().toISOString();
    tasks = tasks.map((task) =>
      task.id === id ? { ...task, ...updates, updatedAt: now } : task
    );
    saveTasks();
    render();
  }

  function deleteTask(id) {
    const now = new Date().toISOString();
    tasks = tasks.map((task) =>
      task.id === id
        ? { ...task, deleted: true, deletedAt: now, updatedAt: now }
        : task
    );
    saveTasks();
    render();
  }

  function clearCompleted() {
    const now = new Date().toISOString();
    tasks = tasks.map((task) =>
      task.completed && !task.deleted
        ? { ...task, deleted: true, deletedAt: now, updatedAt: now }
        : task
    );
    saveTasks();
    render();
  }

  function completeTask(id) {
    const task = tasks.find(t => t.id === id);
    if (!task) return;

    // Mark as completed
    updateTask(id, { completed: true });

    // If recurring, create next occurrence
    if (task.recurrence && task.dueDate) {
      const nextDate = calculateNextDate(task.dueDate, task.recurrence);
      if (nextDate) {
        addTask({
          title: task.title,
          notes: task.notes,
          priority: task.priority,
          category: task.category,
          tag: task.tag,
          dueDate: nextDate,
          dueTime: task.dueTime,
          recurrence: task.recurrence,
        });
      }
    }
  }

  function calculateNextDate(dateString, recurrence) {
    const date = parseLocalDate(dateString);

    switch (recurrence) {
      case "daily":
        date.setDate(date.getDate() + 1);
        break;
      case "weekly":
        date.setDate(date.getDate() + 7);
        break;
      case "monthly":
        date.setMonth(date.getMonth() + 1);
        break;
      default:
        return null;
    }

    return toLocalDateString(date);
  }

  function filterTasks(list) {
    const search = searchInput.value.trim().toLowerCase();
    return list.filter((task) => {
      const matchesDate = !activeDate || task.dueDate === activeDate;
      const matchesSearch =
        !search ||
        [task.title, task.notes, task.tag, task.category]
          .filter(Boolean)
          .some((value) => value.toLowerCase().includes(search));
      const matchesFilter =
        activeFilter === "all" ||
        (activeFilter === "active" && !task.completed) ||
        (activeFilter === "completed" && task.completed);
      const matchesCategory = !activeCategory || task.category === activeCategory;
      return matchesDate && matchesSearch && matchesFilter && matchesCategory;
    });
  }

  function sortTasks(list) {
    return list.slice().sort((a, b) => {
      // Sort by date first
      if (a.dueDate && b.dueDate) {
        const dateCompare = a.dueDate.localeCompare(b.dueDate);
        if (dateCompare !== 0) return dateCompare;

        // If same date, sort by time
        if (a.dueTime && b.dueTime) {
          return a.dueTime.localeCompare(b.dueTime);
        }
        if (a.dueTime) return -1;
        if (b.dueTime) return 1;
      }
      if (a.dueDate) return -1;
      if (b.dueDate) return 1;

      // No dates, sort by priority
      const priorityOrder = { high: 0, medium: 1, low: 2 };
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    });
  }

  function renderTaskList() {
    const visibleTasks = sortTasks(filterTasks(liveTasks()));
    taskList.innerHTML = "";

    visibleTasks.forEach((task) => {
      const listItem = document.createElement("li");
      listItem.className = `task${task.completed ? " completed" : ""}`;

      const checkbox = document.createElement("input");
      checkbox.type = "checkbox";
      checkbox.checked = task.completed;
      checkbox.addEventListener("change", () => {
        if (checkbox.checked) {
          completeTask(task.id);
        } else {
          updateTask(task.id, { completed: false });
        }
      });

      const title = document.createElement("div");
      title.className = "task__title";

      const titleText = document.createElement("span");
      titleText.textContent = task.title;

      const notesText = document.createElement("small");
      notesText.textContent = task.notes || "No notes";
      notesText.className = "muted";

      const meta = document.createElement("div");
      meta.className = "task__meta";

      const category = document.createElement("span");
      category.className = `badge badge-${task.category}`;
      category.textContent = task.category ? `${task.category.charAt(0).toUpperCase() + task.category.slice(1)}` : "No category";

      const priority = document.createElement("span");
      priority.className = `badge badge-priority-${task.priority}`;
      priority.textContent = `Priority: ${task.priority}`;

      const tag = document.createElement("span");
      tag.className = "badge";
      tag.textContent = task.tag ? `${task.tag}` : "No tag";

      const dueDate = document.createElement("span");
      dueDate.className = "badge";
      if (task.dueDate) {
        const dateText = task.dueTime ? `${task.dueDate} ${task.dueTime}` : task.dueDate;
        dueDate.textContent = `Due: ${dateText}`;
      } else {
        dueDate.textContent = "No due date";
      }

      if (task.recurrence) {
        const recurrence = document.createElement("span");
        recurrence.className = "badge badge-recurrence";
        recurrence.textContent = `↻ ${task.recurrence}`;
        meta.append(recurrence);
      }

      meta.append(category, priority, tag, dueDate);
      title.append(titleText, notesText, meta);

      const actions = document.createElement("div");
      actions.className = "task__actions";

      const editButton = document.createElement("button");
      editButton.className = "secondary";
      editButton.textContent = "Edit";
      editButton.addEventListener("click", () => startEdit(task));

      const deleteButton = document.createElement("button");
      deleteButton.className = "danger";
      deleteButton.textContent = "Delete";
      deleteButton.addEventListener("click", () => {
        deleteTask(task.id);
        showUndo(`Deleted "${task.title}"`, [task.id]);
      });

      actions.append(editButton, deleteButton);

      listItem.append(checkbox, title, actions);
      taskList.append(listItem);
    });

  }

  function renderCounts() {
    const counted = liveTasks();
    const categoryStats = counted.reduce((acc, task) => {
      acc[task.category] = (acc[task.category] || 0) + 1;
      return acc;
    }, {});

    let countText = `${counted.length} task${counted.length !== 1 ? "s" : ""}`;
    if (activeCategory) {
      const catCount = categoryStats[activeCategory] || 0;
      countText += ` (${catCount} ${activeCategory})`;
    }
    taskCount.textContent = countText;

    const todayTotal = getTodaysTasks().length;
    todayCount.textContent = todayTotal ? String(todayTotal) : "";

    const weekTotal = Object.values(getWeekTasks())
      .reduce((sum, day) => sum + day.tasks.length, 0);
    if (weekCount) weekCount.textContent = weekTotal ? String(weekTotal) : "";
  }

  // Only the visible panel is rebuilt. Searching used to re-render every view on
  // each keystroke, which is what made large lists feel sluggish.
  function render() {
    renderCounts();
    if (activeView === "today") {
      renderTodaySchedule();
    } else if (activeView === "week") {
      renderWeekView();
    } else {
      renderTaskList();
    }
  }

  function setActiveView(view) {
    activeView = view;
    tabButtons.forEach((button) => {
      const selected = button.dataset.view === view;
      button.classList.toggle("active", selected);
      button.setAttribute("aria-selected", String(selected));
    });
    viewPanels.forEach((panel) => {
      panel.hidden = panel.dataset.panel !== view;
    });
    render();
  }

  function startEdit(task) {
    currentEditingTaskId = task.id;

    // Populate the form
    editTitle.value = task.title;
    editNotes.value = task.notes || "";
    editPriority.value = task.priority;
    editCategory.value = task.category;
    editTag.value = task.tag || "";
    editDueDate.value = task.dueDate || "";
    editDueTime.value = task.dueTime || "";
    editRecurrence.value = task.recurrence || "";

    // Show the modal
    editModal.style.display = "flex";
    editTitle.focus();
  }

  function closeEditModal() {
    editModal.style.display = "none";
    currentEditingTaskId = null;
    editForm.reset();
  }

  function handleEditSubmit(event) {
    event.preventDefault();

    if (!currentEditingTaskId) return;

    updateTask(currentEditingTaskId, {
      title: editTitle.value.trim(),
      notes: editNotes.value.trim(),
      priority: editPriority.value,
      category: editCategory.value,
      tag: editTag.value.trim(),
      dueDate: editDueDate.value,
      dueTime: editDueTime.value,
      recurrence: editRecurrence.value,
    });

    closeEditModal();
  }

  function normalizePriority(value) {
    const cleaned = value.toLowerCase();
    if (["low", "medium", "high"].includes(cleaned)) {
      return cleaned;
    }
    return "medium";
  }

  function normalizeCategory(value) {
    const cleaned = value.toLowerCase();
    if (["work", "home", "research", "clinical", "teaching"].includes(cleaned)) {
      return cleaned;
    }
    return "work";
  }

  function normalizeRecurrence(value) {
    const cleaned = value.toLowerCase();
    if (["daily", "weekly", "monthly"].includes(cleaned)) {
      return cleaned;
    }
    return "";
  }

  function parseQuickCapture(text) {
    let title = text;
    let priority = "medium";
    let category = "work";
    let tag = "";
    let dueDate = "";
    let dueTime = "";
    let notes = "";

    // Extract notes (notes:something or note:something)
    const notesMatch = text.match(/notes?:\s*([^#!]+?)(?=\s+(?:#|!|category:|$))/i);
    if (notesMatch) {
      notes = notesMatch[1].trim();
      title = title.replace(notesMatch[0], "").trim();
    }

    // Extract priority (!high, !medium, !low, or !! for high, ! for medium)
    const priorityMatch = text.match(/!(high|medium|low)|!!+|!/i);
    if (priorityMatch) {
      if (priorityMatch[0] === "!!!") {
        priority = "high";
      } else if (priorityMatch[0] === "!!") {
        priority = "high";
      } else if (priorityMatch[0] === "!") {
        priority = "medium";
      } else {
        priority = priorityMatch[1].toLowerCase();
      }
      title = title.replace(priorityMatch[0], "").trim();
    }

    // Extract category (category:work, or just category name at end)
    const categoryMatch = text.match(/category:\s*(work|home|research|clinical|teaching)/i);
    if (categoryMatch) {
      category = categoryMatch[1].toLowerCase();
      title = title.replace(categoryMatch[0], "").trim();
    } else {
      // Check for category name without prefix at the end
      const implicitCategoryMatch = text.match(/\b(work|home|research|clinical|teaching)\s*$/i);
      if (implicitCategoryMatch) {
        category = implicitCategoryMatch[1].toLowerCase();
        title = title.replace(implicitCategoryMatch[0], "").trim();
      }
    }

    // Extract tag (#something)
    const tagMatch = text.match(/#\w[\w-]*/);
    if (tagMatch) {
      tag = tagMatch[0];
      title = title.replace(tagMatch[0], "").trim();
    }

    // Extract time (improved: 2pm, 2:30pm, 14:00, 8a, 8p, "at 9a", etc.)
    // Match time with optional "at" preposition
    const timeMatch = text.match(/(?:at\s+)?(?:(\d{1,2})(?::(\d{2}))?\s*([ap]m?|AM?|PM?)\b|(\d{1,2}):(\d{2})\b)/i);
    if (timeMatch) {
      let hours, minutes, meridiem;

      if (timeMatch[4]) {
        // Matched HH:MM without meridiem (e.g., "14:00")
        hours = parseInt(timeMatch[4]);
        minutes = timeMatch[5];
        meridiem = null;
      } else {
        // Matched with optional meridiem
        hours = parseInt(timeMatch[1]);
        minutes = timeMatch[2] || "00";
        meridiem = timeMatch[3]?.toLowerCase();

        // Normalize "a" to "am" and "p" to "pm"
        if (meridiem === "a") meridiem = "am";
        if (meridiem === "p") meridiem = "pm";
      }

      // Only process as time if it makes sense (1-12 with am/pm, or 0-23 without)
      const isValidTime = (meridiem && hours >= 1 && hours <= 12) ||
                          (!meridiem && hours >= 0 && hours <= 23);

      if (isValidTime) {
        if (meridiem === "pm" && hours < 12) hours += 12;
        if (meridiem === "am" && hours === 12) hours = 0;

        dueTime = `${hours.toString().padStart(2, "0")}:${minutes}`;
        // Remove the entire match including "at" if present
        title = title.replace(timeMatch[0], "").trim();
      }
    }

    // Extract date (enhanced natural language)
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Handle "in X days/weeks"
    const inDaysMatch = text.match(/\bin\s+(\d+)\s+(day|days|week|weeks)\b/i);
    if (inDaysMatch) {
      const num = parseInt(inDaysMatch[1]);
      const unit = inDaysMatch[2].toLowerCase();
      const targetDate = new Date(today);

      if (unit.startsWith('day')) {
        targetDate.setDate(targetDate.getDate() + num);
      } else if (unit.startsWith('week')) {
        targetDate.setDate(targetDate.getDate() + (num * 7));
      }

      dueDate = toLocalDateString(targetDate);
      title = title.replace(inDaysMatch[0], "").trim();
    }
    // Handle "next [day]" (e.g., "next monday", "next friday")
    else if (text.match(/\bnext\s+(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/i)) {
      const dayMatch = text.match(/\bnext\s+(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/i);
      const targetDayName = dayMatch[1].toLowerCase();
      const daysOfWeek = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
      const targetDayIndex = daysOfWeek.indexOf(targetDayName);
      const currentDayIndex = today.getDay();

      let daysUntil = targetDayIndex - currentDayIndex;
      if (daysUntil <= 0) daysUntil += 7; // Next week

      const targetDate = new Date(today);
      targetDate.setDate(targetDate.getDate() + daysUntil);
      dueDate = toLocalDateString(targetDate);
      title = title.replace(dayMatch[0], "").trim();
    }
    // Handle day names (next occurrence)
    else if (text.match(/\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/i)) {
      const dayMatch = text.match(/\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/i);
      const targetDayName = dayMatch[1].toLowerCase();
      const daysOfWeek = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
      const targetDayIndex = daysOfWeek.indexOf(targetDayName);
      const currentDayIndex = today.getDay();

      let daysUntil = targetDayIndex - currentDayIndex;
      if (daysUntil <= 0) daysUntil += 7; // If today or past, go to next week

      const targetDate = new Date(today);
      targetDate.setDate(targetDate.getDate() + daysUntil);
      dueDate = toLocalDateString(targetDate);
      title = title.replace(dayMatch[0], "").trim();
    }
    // Handle "next week"
    else if (/\bnext\s+week\b/i.test(text)) {
      const nextWeek = new Date(today);
      nextWeek.setDate(nextWeek.getDate() + 7);
      dueDate = toLocalDateString(nextWeek);
      title = title.replace(/\bnext\s+week\b/i, "").trim();
    }
    // Handle "tomorrow"
    else if (/\btomorrow\b/i.test(text)) {
      const tomorrow = new Date(today);
      tomorrow.setDate(tomorrow.getDate() + 1);
      dueDate = toLocalDateString(tomorrow);
      title = title.replace(/\btomorrow\b/i, "").trim();
    }
    // Handle "today"
    else if (/\btoday\b/i.test(text)) {
      dueDate = toLocalDateString(today);
      title = title.replace(/\btoday\b/i, "").trim();
    }
    // Handle YYYY-MM-DD format
    else {
      const dateMatch = text.match(/\b\d{4}-\d{2}-\d{2}\b/);
      if (dateMatch) {
        dueDate = dateMatch[0];
        title = title.replace(dateMatch[0], "").trim();
      }
    }

    return {
      title: title.trim(),
      priority,
      category,
      tag,
      dueDate,
      dueTime,
      notes,
    };
  }

  function handleQuickCapture() {
    const text = quickCaptureInput.value.trim();
    if (!text) return;

    const parsed = parseQuickCapture(text);
    addTask({
      title: parsed.title,
      notes: parsed.notes || "",
      priority: parsed.priority,
      category: parsed.category,
      tag: parsed.tag,
      dueDate: parsed.dueDate,
      dueTime: parsed.dueTime,
      recurrence: "",
    });

    quickCaptureInput.value = "";
  }

  function applyTemplate(templateName) {
    const template = TEMPLATES[templateName];
    if (!template) return;

    taskInput.value = template.title;
    taskNotes.value = template.notes;
    taskPriority.value = template.priority;
    taskCategory.value = template.category;
    taskTag.value = template.tag;

    // Scroll to form
    taskForm.scrollIntoView({ behavior: "smooth", block: "start" });
    taskInput.focus();
  }

  function exportMarkdown() {
    markdownArea.value = MedTodoMarkdown.serializeTasks(
      liveTasks().slice().reverse()
    );
  }

  function importMarkdown() {
    const text = markdownArea.value.trim();
    if (!text) {
      return;
    }
    const imported = MedTodoMarkdown.parseTasks(text).map((task) =>
      normalizeTask({
        ...task,
        id: task.id || generateId(),
        createdAt: task.createdAt || new Date().toISOString(),
      })
    );
    if (!imported.length) {
      return;
    }
    // Same rule as sync: an id that already exists is a newer-wins merge rather
    // than a duplicate.
    tasks = mergeTaskLists(tasks, imported);
    saveTasks();
    render();
  }

  function copyMarkdown() {
    if (!markdownArea.value.trim()) {
      exportMarkdown();
    }
    navigator.clipboard.writeText(markdownArea.value).catch((error) => {
      console.warn("Unable to copy", error);
    });
  }

  function handleFilterClick(event) {
    const target = event.target;
    if (!(target instanceof HTMLButtonElement)) {
      return;
    }
    filterButtons.forEach((button) => button.classList.remove("active"));
    target.classList.add("active");
    activeFilter = target.dataset.filter || "all";
    setActiveView("all");
  }

  function handleCategoryFilterClick(event) {
    const target = event.target;
    if (!(target instanceof HTMLButtonElement)) {
      return;
    }
    categoryFilterButtons.forEach((button) => button.classList.remove("active"));
    target.classList.add("active");
    activeCategory = target.dataset.category || "";
    setActiveView("all");
  }


  // --- Undo -------------------------------------------------------------------
  // Deletes are tombstones rather than removals, so undo is just clearing the
  // flag. A new updatedAt makes the restore win over the delete on other devices.
  let undoIds = [];
  let undoTimer = null;

  function showUndo(message, ids) {
    if (!toast) return;
    undoIds = ids;
    toastMessage.textContent = message;
    toast.hidden = false;
    clearTimeout(undoTimer);
    undoTimer = setTimeout(hideUndo, 8000);
  }

  function hideUndo() {
    if (!toast) return;
    toast.hidden = true;
    undoIds = [];
  }

  function undoDelete() {
    if (!undoIds.length) return;
    const now = new Date().toISOString();
    const ids = new Set(undoIds);
    tasks = tasks.map((task) =>
      ids.has(task.id)
        ? { ...task, deleted: false, deletedAt: "", updatedAt: now }
        : task
    );
    saveTasks();
    render();
    hideUndo();
  }

  function handleClearCompleted() {
    const ids = liveTasks().filter((task) => task.completed).map((task) => task.id);
    if (!ids.length) return;
    clearCompleted();
    showUndo(`Cleared ${ids.length} completed task${ids.length !== 1 ? "s" : ""}`, ids);
  }

  // Event listeners
  taskForm.addEventListener("submit", (event) => {
    event.preventDefault();
    addTask({
      title: taskInput.value.trim(),
      notes: taskNotes.value.trim(),
      priority: taskPriority.value,
      category: taskCategory.value,
      tag: taskTag.value.trim(),
      dueDate: taskDueDate.value,
      dueTime: taskDueTime.value,
      recurrence: taskRecurrence.value,
    });
    taskForm.reset();
    taskPriority.value = "medium";
    taskCategory.value = "work";
  });

  filterButtons.forEach((button) => button.addEventListener("click", handleFilterClick));
  categoryFilterButtons.forEach((button) => button.addEventListener("click", handleCategoryFilterClick));
  clearCompletedButton.addEventListener("click", handleClearCompleted);

  // View tabs
  tabButtons.forEach((button) =>
    button.addEventListener("click", () => setActiveView(button.dataset.view))
  );

  // Searching re-renders on a short delay rather than on every keystroke.
  let searchTimer = null;
  searchInput.addEventListener("input", () => {
    clearTimeout(searchTimer);
    searchTimer = setTimeout(render, 150);
  });

  if (toastAction) toastAction.addEventListener("click", undoDelete);
  exportMarkdownButton.addEventListener("click", exportMarkdown);
  importMarkdownButton.addEventListener("click", importMarkdown);
  copyMarkdownButton.addEventListener("click", copyMarkdown);

  // JSON export/import
  exportJsonButton.addEventListener("click", exportJson);
  importJsonButton.addEventListener("click", () => importJsonFile.click());
  importJsonFile.addEventListener("change", importJson);

  // Quick capture
  quickCaptureBtn.addEventListener("click", handleQuickCapture);
  quickCaptureInput.addEventListener("keypress", (e) => {
    if (e.key === "Enter") {
      handleQuickCapture();
    }
  });

  // Floating quick add button
  floatingQuickAddBtn.addEventListener("click", () => {
    quickCaptureInput.focus();
    quickCaptureInput.scrollIntoView({ behavior: "smooth", block: "center" });
  });

  // Templates
  templateButtons.forEach((button) => {
    button.addEventListener("click", () => {
      const template = button.dataset.template;
      applyTemplate(template);
    });
  });

  // Calendar
  calendarDate.addEventListener("change", () => {
    activeDate = calendarDate.value;
    setActiveView("all");
  });
  clearDateFilterButton.addEventListener("click", () => {
    activeDate = "";
    calendarDate.value = "";
    render();
  });

  // JSON Export/Import Functions
  function exportJson() {
    const dataStr = JSON.stringify({
      tasks: tasks,
      exportDate: new Date().toISOString(),
      version: SCHEMA_VERSION
    }, null, 2);

    const blob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `medtodo-backup-${todayString()}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  function importJson(event) {
    const file = event.target.files[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const data = JSON.parse(e.target.result);

        if (data.tasks && Array.isArray(data.tasks)) {
          // Ask user if they want to merge or replace
          const shouldMerge = confirm(
            `Found ${data.tasks.length} tasks in backup.\n\n` +
            `Click OK to MERGE with existing tasks (${tasks.length}).\n` +
            `Click Cancel to REPLACE all existing tasks.`
          );

          if (shouldMerge) {
            // Merge: Add imported tasks, avoiding duplicates by ID
            const existingIds = new Set(tasks.map(t => t.id));
            const newTasks = data.tasks.filter(t => !existingIds.has(t.id));
            tasks = [...tasks, ...newTasks];
          } else {
            // Replace: Use imported tasks
            tasks = data.tasks;
          }

          saveTasks();
          render();
          alert(`Successfully imported ${data.tasks.length} tasks!`);
        } else {
          alert('Invalid backup file format.');
        }
      } catch (error) {
        alert('Error reading backup file: ' + error.message);
      }

      // Reset file input
      event.target.value = '';
    };

    reader.readAsText(file);
  }

  // ICS Calendar Export
  function exportToCalendar() {
    const tasksWithDates = liveTasks().filter(task => task.dueDate && !task.completed);

    if (tasksWithDates.length === 0) {
      alert('No tasks with due dates to export.\n\nAdd due dates to tasks first, then export to calendar.');
      return;
    }

    // Generate ICS file content
    let icsContent = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//MedTodo//Medical Professional Todo List//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      'X-WR-CALNAME:MedTodo Tasks',
      'X-WR-TIMEZONE:UTC'
    ];

    tasksWithDates.forEach(task => {
      const eventId = task.id.replace(/-/g, '');
      const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

      // Parse due date and time
      const dueDateTime = task.dueTime
        ? new Date(`${task.dueDate}T${task.dueTime}`)
        : new Date(`${task.dueDate}T09:00:00`); // Default to 9 AM if no time

      const dtstart = dueDateTime.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

      // End time: 1 hour after start for tasks with time, all-day for tasks without
      const dtend = task.dueTime
        ? new Date(dueDateTime.getTime() + 60 * 60 * 1000).toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
        : new Date(dueDateTime.getTime() + 24 * 60 * 60 * 1000).toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

      // Build description
      let description = task.notes || task.title;
      if (task.category) description += `\\nCategory: ${task.category}`;
      if (task.tag) description += `\\nTag: ${task.tag}`;
      if (task.priority) description += `\\nPriority: ${task.priority}`;

      // Escape special characters
      description = description.replace(/\n/g, '\\n').replace(/,/g, '\\,');
      const summary = task.title.replace(/,/g, '\\,').replace(/;/g, '\\;');

      // Add event
      icsContent.push('BEGIN:VEVENT');
      icsContent.push(`UID:${eventId}@medtodo`);
      icsContent.push(`DTSTAMP:${now}`);
      icsContent.push(`DTSTART:${dtstart}`);
      icsContent.push(`DTEND:${dtend}`);
      icsContent.push(`SUMMARY:${summary}`);
      icsContent.push(`DESCRIPTION:${description}`);
      icsContent.push(`PRIORITY:${task.priority === 'high' ? '1' : task.priority === 'medium' ? '5' : '9'}`);
      icsContent.push(`CATEGORIES:${task.category || 'Task'}`);

      // Add alarm for high priority tasks (15 minutes before)
      if (task.priority === 'high' && task.dueTime) {
        icsContent.push('BEGIN:VALARM');
        icsContent.push('TRIGGER:-PT15M');
        icsContent.push('ACTION:DISPLAY');
        icsContent.push(`DESCRIPTION:Reminder: ${summary}`);
        icsContent.push('END:VALARM');
      }

      icsContent.push('END:VEVENT');
    });

    icsContent.push('END:VCALENDAR');

    // Create and download file
    const blob = new Blob([icsContent.join('\r\n')], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `medtodo-calendar-${todayString()}.ics`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    alert(`Exported ${tasksWithDates.length} tasks to calendar!\n\nOpen the downloaded .ics file to import into your calendar app.`);
  }

  // Get today's tasks sorted by time
  function getTodaysTasks() {
    const today = todayString();
    return liveTasks()
      .filter(task => task.dueDate === today && !task.completed)
      .sort((a, b) => {
        if (a.dueTime && b.dueTime) {
          return a.dueTime.localeCompare(b.dueTime);
        }
        if (a.dueTime) return -1;
        if (b.dueTime) return 1;
        return 0;
      });
  }

  // Get week's tasks grouped by day
  function getWeekTasks() {
    const today = new Date();
    const weekTasks = {};
    const live = liveTasks();

    for (let i = 0; i < 7; i++) {
      const date = new Date(today);
      date.setDate(today.getDate() + i);
      const dateStr = toLocalDateString(date);
      const dayName = date.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });

      weekTasks[dateStr] = {
        dayName,
        tasks: live
          .filter(task => task.dueDate === dateStr && !task.completed)
          .sort((a, b) => (a.dueTime || '').localeCompare(b.dueTime || ''))
      };
    }

    return weekTasks;
  }

  // Render Today's Schedule
  function renderTodaySchedule() {
    const todayTasks = getTodaysTasks();
    todaySchedule.replaceChildren();

    if (todayTasks.length === 0) {
      todaySchedule.append(el("p", "muted", "No tasks scheduled for today."));
      return;
    }

    todayTasks.forEach((task) => {
      const item = el("div", "schedule-item");
      item.append(el("span", "schedule-time", task.dueTime || "No time"));

      const body = el("div", "schedule-task");
      body.append(el("span", "schedule-title", task.title));

      const meta = el("div", "schedule-meta");
      if (task.category) {
        meta.append(el("span", `badge badge-${task.category}`, task.category));
      }
      if (task.priority) {
        meta.append(el("span", `badge badge-priority-${task.priority}`, task.priority));
      }
      body.append(meta);
      item.append(body);

      todaySchedule.append(item);
    });
  }

  // Render Week View
  function renderWeekView() {
    const entries = Object.entries(getWeekTasks());
    weekView.replaceChildren();

    if (!entries.some(([, data]) => data.tasks.length > 0)) {
      weekView.append(el("p", "muted", "No tasks scheduled this week."));
      return;
    }

    entries.forEach(([, data]) => {
      const day = el("div", "week-day");
      const header = el("div", "week-day-header");
      header.append(el("span", "week-day-name", data.dayName));

      if (data.tasks.length === 0) {
        header.append(el("span", "week-day-count muted", "No tasks"));
        day.append(header);
        weekView.append(day);
        return;
      }

      header.append(
        el(
          "span",
          "week-day-count",
          `${data.tasks.length} task${data.tasks.length !== 1 ? "s" : ""}`
        )
      );
      day.append(header);

      const list = el("div", "week-day-tasks");
      data.tasks.forEach((task) => {
        const row = el("div", "week-task");
        row.append(el("span", "week-task-time", task.dueTime || "—"));
        row.append(el("span", "week-task-title", task.title));
        row.append(
          el("span", `badge badge-priority-${task.priority}`, task.priority)
        );
        list.append(row);
      });
      day.append(list);

      weekView.append(day);
    });
  }

  // Calendar export event listener
  exportCalendarButton.addEventListener("click", exportToCalendar);

  // Edit modal event listeners
  editForm.addEventListener("submit", handleEditSubmit);
  closeModalBtn.addEventListener("click", closeEditModal);
  cancelEditBtn.addEventListener("click", closeEditModal);

  // Close modal when clicking outside
  editModal.addEventListener("click", (e) => {
    if (e.target === editModal) {
      closeEditModal();
    }
  });

  // Close modal on Escape key. Named so destroy() can detach it -- this one is on
  // document, and an Obsidian pane can be opened and closed repeatedly.
  function handleGlobalKeydown(e) {
    if (e.key === "Escape" && editModal.style.display === "flex") {
      closeEditModal();
    }
  }
  document.addEventListener("keydown", handleGlobalKeydown);

  // Bridge for sync.js, which is loaded after this file. `tasks` is a module-level
  // `let`, so it is not reachable from another script without an explicit accessor.
  window.MedTodoStore = {
    getTasks: () => tasks,
    setTasks(next) {
      tasks = next.map(normalizeTask);
      saveTasks();
      render();
    },
    mergeTaskLists,
    normalizeTask,
  };

  // --- Seasonal theme ---------------------------------------------------------
  // Meteorological seasons, northern hemisphere. The chip in the header cycles
  // through Auto and the four seasons, so anyone south of the equator (or just
  // bored of the current one) can pin whichever they like.
  const SEASON_KEY = "todo.season";
  const SEASONS = ["spring", "summer", "autumn", "winter"];
  const SEASON_LABELS = {
    spring: "🌸 Spring",
    summer: "☀️ Summer",
    autumn: "🍂 Autumn",
    winter: "❄️ Winter",
  };
  const SEASON_THEME_COLORS = {
    spring: "#7fb069",
    summer: "#f0a830",
    autumn: "#c96a2b",
    winter: "#5b8db8",
  };

  function seasonForDate(date) {
    const month = date.getMonth();
    if (month >= 2 && month <= 4) return "spring";
    if (month >= 5 && month <= 7) return "summer";
    if (month >= 8 && month <= 10) return "autumn";
    return "winter";
  }

  function loadSeasonPreference() {
    try {
      const stored = storage.getItem(SEASON_KEY);
      return stored === "auto" || SEASONS.includes(stored) ? stored : "auto";
    } catch (error) {
      return "auto";
    }
  }

  function resolveSeason(preference, date) {
    return SEASONS.includes(preference) ? preference : seasonForDate(date);
  }

  function applySeason() {
    const preference = loadSeasonPreference();
    const season = resolveSeason(preference, new Date());
    const pinned = preference !== "auto";

    const onWebPage =
      typeof document !== "undefined" &&
      document.body &&
      document.body.classList &&
      document.body.classList.contains("medtodo-page");
    (onWebPage ? document.documentElement : root).dataset.season = season;

    const themeMeta = document.querySelector('meta[name="theme-color"]');
    if (themeMeta) themeMeta.setAttribute("content", SEASON_THEME_COLORS[season]);

    if (seasonChip) {
      seasonChip.textContent = SEASON_LABELS[season];
      seasonChip.classList.toggle("season-chip--pinned", pinned);
      seasonChip.title = pinned
        ? `Season pinned to ${season}. Click to change; keep clicking to return to automatic.`
        : `${SEASON_LABELS[season].split(" ")[1]}, following the calendar. Click to pick a different one.`;
    }
    return season;
  }

  function cycleSeason() {
    const order = ["auto"].concat(SEASONS);
    const next = order[(order.indexOf(loadSeasonPreference()) + 1) % order.length];
    try {
      storage.setItem(SEASON_KEY, next);
    } catch (error) {
      console.warn("Unable to save season preference", error);
    }
    applySeason();
  }

  if (seasonChip) seasonChip.addEventListener("click", cycleSeason);
  applySeason();

  // Initial render
  setActiveView(activeView);


  return {
    SEASONS,
    toLocalDateString,
    parseLocalDate,
    todayString,
    normalizeTask,
    mergeTaskLists,
    liveTasks,
    getTodaysTasks,
    getWeekTasks,
    addTask,
    deleteTask,
    updateTask,
    clearCompleted,
    completeTask,
    calculateNextDate,
    renderTaskList,
    renderCounts,
    render,
    renderTodaySchedule,
    renderWeekView,
    setActiveView,
    undoDelete,
    showUndo,
    hideUndo,
    handleClearCompleted,
    seasonForDate,
    resolveSeason,
    applySeason,
    cycleSeason,
    parseQuickCapture,
    exportMarkdown,
    importMarkdown,
    getActiveView: () => activeView,
    getTasks: () => tasks,
    setTasks: (next) => {
      tasks = next.map(normalizeTask);
      saveTasks();
      render();
    },
    destroy: () => {
      clearTimeout(searchTimer);
      clearTimeout(undoTimer);
      document.removeEventListener("keydown", handleGlobalKeydown);
    },
  };
}

// --- Exports ----------------------------------------------------------------
if (typeof module === "object" && module.exports) {
  module.exports = { createMedTodoApp };
}
if (typeof globalThis !== "undefined") {
  globalThis.createMedTodoApp = createMedTodoApp;
}

// Web bootstrap. Skipped when there is no page to mount into (the Obsidian
// plugin and the test harness create the app themselves).
if (typeof document !== "undefined" && typeof MedTodoUI !== "undefined") {
  const appRoot = document.querySelector("#app-root");
  if (appRoot) {
    MedTodoUI.mount(appRoot);
    createMedTodoApp({ root: appRoot, storage: window.localStorage });
  }
}

})(undefined, undefined);

// ===== Obsidian shell =========================================================
// Everything above this line is the shared app, byte-identical to what the web
// page loads. This file is the only Obsidian-specific code.

const { Plugin, ItemView, PluginSettingTab, Setting, Notice } = require("obsidian");

const VIEW_TYPE = "medtodo-view";
const TASKS_KEY = "todo.tasks";
const DEFAULT_SETTINGS = { tasksPath: "Tasks.md" };

// Categories that must never be written into the vault. The vault syncs
// (iCloud, Obsidian Sync, Dropbox...), and whether that is end-to-end encrypted
// is not something this plugin can know, so clinical tasks stay in Obsidian's
// own localStorage -- which lives in the application's data directory, outside
// the vault folder, and is therefore never picked up by vault sync.
const PRIVATE_CATEGORIES = ["clinical"];

const FILE_HEADER = [
  "---",
  "medtodo: tasks",
  "---",
  "",
  "> [!info] Managed by MedTodo",
  "> Edit these lines by hand if you like -- titles, checkboxes, tags and the",
  "> metadata in parentheses are all read back. The trailing comment holds ids",
  "> and timestamps; leave it alone and tasks keep their identity.",
  "",
].join("\n");

function isPrivate(task) {
  return PRIVATE_CATEGORIES.indexOf(task.category) !== -1;
}

// --- Storage -----------------------------------------------------------------
// The app asks for storage synchronously, so reads come from a cache primed
// before the view is created and writes are flushed to the vault in the
// background.
async function createVaultStorage(plugin) {
  const localKey = "medtodo.local:" + plugin.app.vault.getName();
  const cache = new Map();
  let flushTimer = null;

  function readLocal() {
    try {
      const raw = window.localStorage.getItem(localKey);
      const parsed = raw ? JSON.parse(raw) : [];
      return Array.isArray(parsed) ? parsed : [];
    } catch (error) {
      console.error("MedTodo: could not read device-local tasks", error);
      return [];
    }
  }

  async function readVault() {
    const file = plugin.app.vault.getAbstractFileByPath(plugin.settings.tasksPath);
    if (!file || !("extension" in file)) return [];
    const text = await plugin.app.vault.read(file);
    return MedTodoMarkdown.parseTasks(text).map((task) => {
      // Lines typed by hand have no id yet.
      if (!task.id) {
        const now = new Date().toISOString();
        task.id = "md-" + Math.random().toString(36).slice(2, 10) + Date.now().toString(36);
        task.createdAt = task.createdAt || now;
        task.updatedAt = task.updatedAt || now;
      }
      return task;
    });
  }

  async function prime() {
    const combined = (await readVault()).concat(readLocal());
    cache.set(TASKS_KEY, JSON.stringify({ version: 2, tasks: combined }));
  }

  async function flush() {
    const raw = cache.get(TASKS_KEY);
    if (!raw) return;
    let all = [];
    try {
      all = (JSON.parse(raw) || {}).tasks || [];
    } catch (error) {
      console.error("MedTodo: could not parse tasks before saving", error);
      return;
    }

    // Deleted tasks leave the note entirely -- a removed line is what a delete
    // looks like in a checklist. Their tombstones stay device-local so a delete
    // still wins over a stale copy the app may merge later.
    const forVault = all.filter((task) => !task.deleted && !isPrivate(task));
    const forDevice = all.filter((task) => task.deleted || isPrivate(task));

    try {
      window.localStorage.setItem(localKey, JSON.stringify(forDevice));
    } catch (error) {
      console.error("MedTodo: could not save device-local tasks", error);
    }

    const body = FILE_HEADER + MedTodoMarkdown.serializeTasks(forVault) + "\n";
    plugin.suppressReload = true;
    try {
      const file = plugin.app.vault.getAbstractFileByPath(plugin.settings.tasksPath);
      if (file && "extension" in file) {
        await plugin.app.vault.modify(file, body);
      } else {
        await plugin.app.vault.create(plugin.settings.tasksPath, body);
      }
    } catch (error) {
      new Notice("MedTodo could not write " + plugin.settings.tasksPath);
      console.error("MedTodo: vault write failed", error);
    } finally {
      // Let the vault's own change event settle before listening again.
      window.setTimeout(() => { plugin.suppressReload = false; }, 300);
    }
  }

  await prime();

  return {
    prime,
    flushNow: flush,
    getItem(key) {
      if (key === TASKS_KEY) return cache.has(key) ? cache.get(key) : null;
      return window.localStorage.getItem(localKey + ":" + key);
    },
    setItem(key, value) {
      if (key === TASKS_KEY) {
        cache.set(key, String(value));
        window.clearTimeout(flushTimer);
        flushTimer = window.setTimeout(flush, 400);
        return;
      }
      window.localStorage.setItem(localKey + ":" + key, String(value));
    },
  };
}

// --- View --------------------------------------------------------------------
class MedTodoView extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.instance = null;
  }
  getViewType() { return VIEW_TYPE; }
  getDisplayText() { return "Tasks"; }
  getIcon() { return "checkmark"; }

  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    const root = container.createDiv({ cls: "medtodo-root" });
    MedTodoUI.mount(root);
    this.instance = createMedTodoApp({ root, storage: this.plugin.storage });
    this.plugin.views.add(this);
  }

  async onClose() {
    this.plugin.views.delete(this);
    if (this.instance) {
      this.instance.destroy();
      this.instance = null;
    }
  }

  // Called when the tasks note changes underneath us -- a hand edit, or another
  // device's copy arriving through vault sync.
  async refreshFromVault() {
    if (!this.instance) return;
    await this.plugin.storage.prime();
    const raw = this.plugin.storage.getItem(TASKS_KEY);
    try {
      this.instance.setTasks((JSON.parse(raw) || {}).tasks || []);
    } catch (error) {
      console.error("MedTodo: could not reload tasks", error);
    }
  }
}

// --- Settings ----------------------------------------------------------------
class MedTodoSettingTab extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();

    new Setting(containerEl)
      .setName("Tasks note")
      .setDesc("Path inside the vault where tasks are stored as a checklist.")
      .addText((text) =>
        text
          .setPlaceholder("Tasks.md")
          .setValue(this.plugin.settings.tasksPath)
          .onChange(async (value) => {
            this.plugin.settings.tasksPath = value.trim() || DEFAULT_SETTINGS.tasksPath;
            await this.plugin.saveSettings();
          })
      );

    const note = containerEl.createEl("div", { cls: "setting-item-description" });
    note.createEl("p", {
      text:
        "Tasks in the Clinical category are never written to this note. They are " +
        "kept in Obsidian's own storage, which lives outside the vault folder and " +
        "is not picked up by vault sync.",
    });
    note.createEl("p", {
      text:
        "Everything else in the note syncs however your vault syncs. If that is " +
        "iCloud Drive, it is only end-to-end encrypted when Advanced Data " +
        "Protection is enabled on your Apple account.",
    });
  }
}

// --- Plugin ------------------------------------------------------------------
module.exports = class MedTodoPlugin extends Plugin {
  async onload() {
    this.views = new Set();
    this.suppressReload = false;
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.storage = await createVaultStorage(this);

    this.registerView(VIEW_TYPE, (leaf) => new MedTodoView(leaf, this));
    this.addRibbonIcon("checkmark", "Open tasks", () => this.activateView());
    this.addCommand({
      id: "open-tasks",
      name: "Open tasks",
      callback: () => this.activateView(),
    });
    this.addSettingTab(new MedTodoSettingTab(this.app, this));

    // Pick up hand edits and copies arriving from other devices.
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (this.suppressReload) return;
        if (file.path !== this.settings.tasksPath) return;
        this.views.forEach((view) => view.refreshFromVault());
      })
    );
  }

  async onunload() {
    // Make sure a pending debounced write is not lost on the way out.
    if (this.storage) await this.storage.flushNow();
  }

  async saveSettings() {
    await this.saveData(this.settings);
  }

  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    if (existing.length) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    await leaf.setViewState({ type: VIEW_TYPE, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
};

// Exposed for the test suite. Not part of the plugin's surface in Obsidian.
module.exports.__internals = { createVaultStorage, isPrivate, FILE_HEADER, TASKS_KEY };
