#!/usr/bin/env node
// Assembles the Obsidian plugin from the shared source files.
//
// This is a concatenator, not a bundler: no dependencies, no transpiling. It
// exists only because Obsidian loads a single main.js, while the web app loads
// the same code as separate <script> tags.
//
//   node tools/build-plugin.js

const fs = require("fs");
const path = require("path");

const repo = path.join(__dirname, "..");
const outDir = path.join(repo, "obsidian-plugin");
const SCOPE = ".medtodo-root";

// --- JavaScript -------------------------------------------------------------
// The shared files are UMD-ish and assign to module.exports when it exists.
// Inside the plugin bundle module.exports is the plugin class, so each file is
// wrapped with `module` shadowed to undefined; they then fall back to defining
// their globals, which is what the shell below consumes.
function wrap(file) {
  const source = fs.readFileSync(path.join(repo, file), "utf8");
  return [
    `// ===== ${file} ${"=".repeat(Math.max(0, 60 - file.length))}`,
    "(function (module, exports) {",
    source,
    "})(undefined, undefined);",
    "",
  ].join("\n");
}

// sync.js is deliberately omitted: inside Obsidian the vault is the sync
// mechanism, so the GitHub layer would be redundant machinery.
const SHARED = ["ui.js", "todo-markdown.js", "app.js"];

const banner = `/* MedTodo for Obsidian -- generated by tools/build-plugin.js. Do not edit.
   Edit the shared sources in the repository root and rebuild. */\n\n`;

const shell = fs.readFileSync(path.join(outDir, "plugin-src.js"), "utf8");
const mainJs = banner + SHARED.map(wrap).join("\n") + "\n" + shell;
fs.writeFileSync(path.join(outDir, "main.js"), mainJs);

// --- CSS --------------------------------------------------------------------
// Every selector is scoped under the plugin's container. Without this, rules
// like `button { ... }` would restyle the whole Obsidian interface.
function scopeSelector(selectorList) {
  const parts = selectorList.split(",").map((s) => s.trim()).filter(Boolean);
  const scoped = parts.map((part) => {
    // Rules that only apply to the standalone page have no meaning in a pane.
    if (part.startsWith("body.medtodo-page")) return null;
    if (part === ":root" || part === "body" || part === "html") return SCOPE;
    if (part.startsWith(":root")) return SCOPE + part.slice(":root".length);
    const notPage = "body:not(.medtodo-page)";
    if (part.startsWith(notPage)) {
      const rest = part.slice(notPage.length).trim();
      return rest ? `${SCOPE} ${rest}` : SCOPE;
    }
    if (part.startsWith("body")) {
      const rest = part.slice("body".length);
      return rest.startsWith(" ") ? `${SCOPE} ${rest.trim()}` : SCOPE + rest;
    }
    if (part.startsWith("[")) return SCOPE + part;
    if (part.startsWith("*")) return `${SCOPE} *${part.slice(1)}`;
    return `${SCOPE} ${part}`;
  }).filter(Boolean);
  return scoped.length ? scoped.join(",\n") : null;
}

function scopeCss(css) {
  // Comments are stripped first: the scanner accumulates everything before a
  // "{" as the selector, so a comment sitting above a rule would otherwise be
  // parsed as part of it (and any comma inside it as a selector separator).
  css = css.replace(/\/\*[\s\S]*?\*\//g, "");
  let out = "";
  let i = 0;
  let buffer = "";
  let depth = 0;
  let inKeyframes = false;

  while (i < css.length) {
    const ch = css[i];
    if (ch === "{") {
      const prelude = buffer.trim();
      buffer = "";
      if (depth === 0 && prelude.startsWith("@")) {
        // Pass at-rules through; their contents are handled at depth 1.
        inKeyframes = /^@(-\w+-)?keyframes/.test(prelude);
        out += prelude + " {";
        depth++;
      } else if (inKeyframes) {
        out += prelude + " {";
        depth++;
      } else {
        const scoped = scopeSelector(prelude);
        if (scoped === null) {
          // Dropped rule: skip to its matching close brace.
          let d = 1;
          i++;
          while (i < css.length && d > 0) {
            if (css[i] === "{") d++;
            else if (css[i] === "}") d--;
            i++;
          }
          continue;
        }
        out += scoped + " {";
        depth++;
      }
      i++;
      continue;
    }
    if (ch === "}") {
      out += buffer + "}";
      buffer = "";
      depth--;
      if (depth === 0) inKeyframes = false;
      i++;
      continue;
    }
    buffer += ch;
    i++;
  }
  return out + buffer;
}

const overrides = `

/* ---- Plugin-only adjustments ------------------------------------------- */
/* The pane is the app; a floating button over Obsidian's UI is out of place. */
${SCOPE} .floating-btn { display: none !important; }

/* Sync is handled by the vault here, so the GitHub panel is not bundled. */
${SCOPE} #sync-card { display: none !important; }

/* Fill the pane rather than centring a page-width column in it. */
${SCOPE} .app { max-width: none; padding: 16px 16px 32px; }
${SCOPE} { display: block; height: 100%; overflow-y: auto; }
`;

const css = fs.readFileSync(path.join(repo, "styles.css"), "utf8");
fs.writeFileSync(path.join(outDir, "styles.css"),
  "/* Generated by tools/build-plugin.js. Do not edit. */\n" + scopeCss(css) + overrides);

console.log(`main.js    ${mainJs.length} bytes (${SHARED.join(", ")} + shell)`);
console.log(`styles.css scoped under ${SCOPE}`);
